services:
  app:
    image: mp740429299/guogai-infinite-canvas:latest
    container_name: infinite-canvas
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    ports:
      - "3000:3000"
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true

  watchtower:
    image: containrrr/watchtower:latest
    container_name: infinite-canvas-watchtower
    command: --cleanup --label-enable --interval 300
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
